"""Add linkedin page media

Revision ID: 067585149665
Revises: 0001
Create Date: 2026-09-27 18:48:49.576342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '067585149665'
down_revision: Union[str, Sequence[str], None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_campaign_assets_product_id'), 'campaign_assets', ['product_id'], unique=False)
    op.create_foreign_key(None, 'campaign_assets', 'page_screenshots', ['source_screenshot_id'], ['id'])
    op.create_index(op.f('ix_crawled_pages_crawl_job_id'), 'crawled_pages', ['crawl_job_id'], unique=False)
    op.add_column('linkedin_product_pages', sa.Column('logo_url', sa.String(), nullable=True))
    op.add_column('linkedin_product_pages', sa.Column('banner_url', sa.String(), nullable=True))
    op.add_column('linkedin_product_pages', sa.Column('downloadable_url', sa.String(), nullable=True))
    op.create_index(op.f('ix_social_posts_campaign_id'), 'social_posts', ['campaign_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_social_posts_campaign_id'), table_name='social_posts')
    op.drop_column('linkedin_product_pages', 'downloadable_url')
    op.drop_column('linkedin_product_pages', 'banner_url')
    op.drop_column('linkedin_product_pages', 'logo_url')
    op.drop_index(op.f('ix_crawled_pages_crawl_job_id'), table_name='crawled_pages')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'campaign_assets', type_='foreignkey')
    op.drop_index(op.f('ix_campaign_assets_product_id'), table_name='campaign_assets')
    # ### end Alembic commands ###
